<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class UserAdminSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = \Faker\Factory::create();
        DB::table('users')->insert([
            ['name'=>'Martin',
            'surname'=>'Klaučo',
            'email'=>'martin.klauco@stuba.sk',
            'email_verified_at'=>now(),
            'password'=>'$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
            'remember_token'=>Str::random(10),
            'is_admin'=>'1',
            'tel_number' => '',
            'street' => 'Radlinského',
            'street_number' => '9',
            'city' => 'Bratislava',
            'postcode' => '81237',
            'country_id' => '158',

            ],
            
            ['name'=>'Ľuboš',
            'surname'=>'Čirka',
            'email'=>'lubos.cirka@stuba.sk',
            'email_verified_at'=>now(),
            'password'=>'$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
            'remember_token'=>Str::random(10),
            'is_admin'=>'1',
            'tel_number' => '',
            'street' => 'Radlinského',
            'street_number' => '9',
            'city' => 'Bratislava',
            'postcode' => '81237',
            'country_id' => '158',
            ],

            ['name'=>'Denisa',
            'surname'=>'Chowaniecova',
            'email'=>'xchowaniecova@stuba.sk',
            'email_verified_at'=>now(),
            'password'=>'$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
            'remember_token'=>Str::random(10),
            'is_admin'=>'1',
            'tel_number' => '+421915501123',
            'street' => 'Lánska',
            'street_number' => '9',
            'city' => 'Považská Bystrica',
            'postcode' => '01701',
            'country_id' => '158',
            ],

            ['name'=>'Trieu',
            'surname'=>'Nguyen Hai',
            'email'=>'xnguyenhai@stuba.sk',
            'email_verified_at'=>now(),
            'password'=>'$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
            'remember_token'=>Str::random(10),
            'is_admin'=>'1',
            'tel_number' => '',
            'street' => 'Zámocká',
            'street_number' => '8',
            'city' => 'Bratislava',
            'postcode' => '81101',
            'country_id' => '158',
            ],

            ['name'=>'Meno',
            'surname'=>'Priezvisko',
            'email'=>'xpriezvisko@stuba.sk',
            'email_verified_at'=>now(),
            'password'=>'$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
            'remember_token'=>Str::random(10),
            'is_admin'=>'0',
            'tel_number' => '',
            'street' => 'Prins Mauritssingel',
            'street_number' => '48',
            'city' => 'Rotterdam',
            'postcode' => '3043',
            'country_id' => '123',
            ],

            ['name'=>'Karol',
            'surname'=>'Mrkva',
            'email'=>'xmrkva@stuba.sk',
            'email_verified_at'=>now(),
            'password'=>'$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
            'remember_token'=>Str::random(10),
            'is_admin'=>'0',
            'tel_number' => '',
            'street' => 'Farského',
            'street_number' => '17',
            'city' => 'Olomouc',
            'postcode' => '77900',
            'country_id' => '45',
            ],

            ['name'=>'Karolína',
            'surname'=>'Mrkvová',
            'email'=>'xmrkvova@stuba.sk',
            'email_verified_at'=>now(),
            'password'=>'$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
            'remember_token'=>Str::random(10),
            'is_admin'=>'0',
            'tel_number' => '',
            'street' => 'Farského',
            'street_number' => '17',
            'city' => 'Olomouc',
            'postcode' => '77900',
            'country_id' => '45',
            ],

            ['name'=>'Frederika',
            'surname'=>'Salová',
            'email'=>'xsalova@stuba.sk',
            'email_verified_at'=>now(),
            'password'=>'$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
            'remember_token'=>Str::random(10),
            'is_admin'=>'0',
            'tel_number' => '',
            'street' => 'Bottova',
            'street_number' => '5',
            'city' => 'Brezno',
            'postcode' => '97701',
            'country_id' => '158',
            ],

            ['name'=>'Maria',
            'surname'=>'Waloska',
            'email'=>'xwalovska@stuba.sk',
            'email_verified_at'=>now(),
            'password'=>'$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
            'remember_token'=>Str::random(10),
            'is_admin'=>'0',
            'tel_number' => '+4880998768965',
            'street' => 'Wierzynka',
            'street_number' => '24',
            'city' => 'Wieliczka',
            'postcode' => '32020',
            'country_id' => '140',
            ],

            ['name'=>'Oliver',
            'surname'=>'Szatmary',
            'email'=>'xszatmary@stuba.sk',
            'email_verified_at'=>now(),
            'password'=>'$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
            'remember_token'=>Str::random(10),
            'is_admin'=>'0',
            'tel_number' => '+3680900888968',
            'street' => 'Liga u.',
            'street_number' => '4',
            'city' => 'Szeged',
            'postcode' => '6726',
            'country_id' => '76',
            ],

            ['name'=>'Albert',
            'surname'=>'Svit',
            'email'=>'xsvit@stuba.sk',
            'email_verified_at'=>now(),
            'password'=>'$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
            'remember_token'=>Str::random(10),
            'is_admin'=>'0',
            'tel_number' => '+4880998768965',
            'street' => 'Pavlovičová',
            'street_number' => '1',
            'city' => 'Svidník',
            'postcode' => '08901',
            'country_id' => '158',
            ],

        ]);
    }
}
